export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-authBG px-1/8 py-1/12 h-svh rounded-md">
        <div className="flex h-full shadow-md rounded-md">
          <div className="w-3/5 bg-white rounded-l-md p-16">{children}</div>
          <div className="bg-gradient-to-r from-authGradient1 to-authGradient2 w-2/5 h-full rounded-r-md"></div>
        </div>
      </body>
    </html>
  );
}
